{
 "title": "Status",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Publizon",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(eReolenApp_publizon_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Elements in feed (frontpage)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eReolenApp_ereolen_feed_total", "legendFormat": "eReolen" },
    {
     "expr": "eReolenApp_ereolengo_feed_total",
     "legendFormat": "eReolenGo"
    }
   ]
  },
  {
   "title": "Date well search time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(eReolenApp_datawell_search_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "Request"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(eReolenApp_datawell_reported_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "Reported"
    }
   ]
  },
  {
   "title": "eReolen online",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "eReolenApp_ereolen_up" }
   ]
  },
  {
   "title": "eReolenGo online",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eReolenApp_ereolengo_up" }
   ]
  },
  {
   "title": "Datawell online",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "datawell-up",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "eReolenApp_datawell_up",
     "legendFormat": "Reported",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Publizon online",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "eReolenApp_publizon_up" }
   ]
  }
 ]
}